name: Bootable JAR CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: false
    name: JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Run Integration Tests
        run: mvn verify -P bootable,github-arquillian -Dchromedriver=$CHROMEWEBDRIVER/chromedriver
